name: Linting and Testing
on:
  push:
    branches: "**"
  pull_request:
    branches: [main]
jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Cache dependencies 
        id: deps
        uses: actions/checkout@v3
        env:
          cache-name: cache-dependencies
        with:
          path: ~/.npm
          key: npm-deps_${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pack-lock.json') }}
          restore-keys: |
            npm-deps_${{ runner.os }}-${{ env.cache-name }}-
            npm-deps_${{ runner.os }}-
      - if: ${{ steps.deps.outputs.cache-hit != 'true' }}
        name: Could find cache, listing state of node modules
        continue-on-error: true
        run: npm list
      - name: Install
        run: npm ci
      - name: Lint and Format
        run: npm run ci:lint
      - name: Test
        run: npm run ci:test
