name: Linting and Testing
on:
  push:
    branches: "**"
  pull_request:
    branches: [main]
jobs:
  build:
    name: Initialize and run
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Initialize Node.js
        id: node-version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Cache npm
        id: deps
        uses: actions/cache@v3
        env:
          cache-name: cache-npm
        with:
          path: ~/.npm
          key: npm-deps_${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-deps_${{ runner.os }}-${{ env.cache-name }}-
            npm-deps_${{ runner.os }}-
      - if: ${{ steps.deps.outputs.cache-hit != 'true' }}
        name: Could not find cache, listing state of node modules
        continue-on-error: true
        run: npm list
      - name: Install
        run: npm ci
      - name: Lint and Format
        run: npm run ci:lint
      - name: Unit test
        run: npm run ci:test
